apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apps.fullname" . }}
  labels:
    k8s-app: {{ include "apps.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      k8s-app: {{ include "apps.name" . }}
  template:
    metadata:
      labels:
        k8s-app: {{ include "apps.name" . }}
    spec:
      volumes:
        - name: images-path
          persistentVolumeClaim: 
            claimName: pvc
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: images-path
              mountPath: /home/images
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
        - name: registrypass
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
