- hosts: k8s-cluster01
  vars:
    projectName: ""
    imageName: ""
    namespace: ""
    imageTag: ""
  tasks:
  - name: Change directory
    command: chdir=/root/deployment/deployments git pull
    ignore_errors: no
  - name: Delete Deployed Before
    command: "helm delete --purge {{ projectName }}"
    ignore_errors: yes
  - name: Deploy Apps Maven Docker
    command: "helm install --name={{ projectName }} --namespace={{ namespace }} /root/deployment/{{ projectName }} --set image.repository={{ imageName }} --set image.tag={{ imageTag }} --set namespace={{ namespace }}"
    ignore_errors: no

